# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'maven'
    - name: Build dartsass plugin
      run: mvn -B install --file dartsass-maven-plugin/pom.xml
    - name: Build with Maven
      run: mvn -B package --file site/pom.xml
        
    - name: Deploy with rsync
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_PORT: "19" 
        ARGS: "-a"
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: "scrumy"
        TARGET: "/tmp/scrumy"        
        SCRIPT_AFTER: |
            rsync -r /tmp/scrumy/site/target/quarkus-app/* /usr/local/scrumy
            sudo systemctl restart scrumy